from oweb.tests.views.account_delete import *
from oweb.tests.views.account_settings_commit import *
from oweb.tests.views.create_account import *
from oweb.tests.views.home import *
from oweb.tests.views.item_update import *
from oweb.tests.views.moon_create import *
from oweb.tests.views.moon_settings_commit import *
from oweb.tests.views.planet_create import *
from oweb.tests.views.planet_delete import *
from oweb.tests.views.planet_settings_commit import *
